### ISSUE TITLE
Duplicate metrics when scraping containers started using docker-compose

### ISSUE THREAD

**Issue by abhishekbajpayee** [AlexRudd/docker_watch#4]

**Comment by abhishekbajpayee** [comment]
I have been running docker_watch on an EC2 instances for ~12 hours now and the prometheus volume is already 1.8G in size. Also, prometheus container logs are a continuous stream of:
```
time="2017-03-10T16:37:55Z" level=warning msg="Error on ingesting samples with different value but same timestamp" numDropped=50 source="scrape.go:520" 
time="2017-03-10T16:38:00Z" level=warning msg="Error on ingesting samples with different value but same timestamp" numDropped=50 source="scrape.go:520" 
time="2017-03-10T16:38:05Z" level=warning msg="Error on ingesting samples with different value but same timestamp" numDropped=50 source="scrape.go:520" 
```

Is it possible docker_watch is exporting data too fast? Is there a way to set time intervals at which docker_watch polls stats?

**Comment by abhishekbajpayee** [comment]
I am also running `node_exporter` along with `docker_watch` and just validated that the error is due to `docker_watch` and goes away if I remove it from the stack.

**Comment by alexrudd** [comment]
docker_watch only queries docker for metrics when scraped, and doesn't cache them. Could you provide me with some information regarding your setup?

* Prometheus config
* Prometheus version
* docker_watch runtime flags

and anything else you think is relevant.

The error you're reporting comes from [this section of code.](https://github.com/prometheus/prometheus/blob/8809735d7f53926fd60a37ac7f41399543d7fd36/retrieval/scrape.go#L524) Which implies multiple duplicate metrics have been reported by docker_watch for the same timestamp.

I checked the code to see if i'd accidentally duplicated any of the exported metrics but there's nothing obvious.

An easy way for you to check if there are duplicates in your scrapes would be with a command like this:

```sh
curl -s localhost:9100/metrics | grep -v '^#.*' | awk '{for (i=1; i<=NF-1; i++) printf $i; print ""}' | uniq -c
```

Replace `localhost:9100` with the address of your docker_watch instance and this will output all the metrics from the scrape prefixed with the number of times they occurred.

**Comment by abhishekbajpayee** [comment]
On running:
```
curl -s localhost:9100/metrics | grep -v '^#.*' | awk '{for (i=1; i<=NF-1; i++) printf $i; print ""}' | uniq -c
```

I see the following output (omitting lines starting with 1):
```
      ...
      5 dw_inspect_process_id
      ...
      5 dw_inspect_started_timestamp
      ...
      5 dw_inspect_state
      ...
      20 dw_stats_blkio_op_total_bytes
      ...
      5 dw_stats_cpu_throttled_periods_total
      ...
      5 dw_stats_cpu_usage_total_nanoseconds
      ...
      5 dw_stats_memory_limit_bytes
      ...
      5 dw_stats_memory_usage_bytes
      ...
      5 dw_stats_network_rx_total_bytes
      ...
      5 dw_stats_network_rx_total_dropped
      ...
      5 dw_stats_network_rx_total_errors
      ...
      5 dw_stats_network_rx_total_packets
      ...
      5 dw_stats_network_tx_total_bytes
      ...
      5 dw_stats_network_tx_total_dropped
      ...
      5 dw_stats_network_tx_total_errors
      ...
      5 dw_stats_network_tx_total_packets
      ...
```

I am assuming those are the repeated stats that are being rejected?

Another thing I noticed recently which might be related to this issue is that `docker_watch` is unable to pull stats from containers in the docker compose stack i.e. any containers started using compose are not visible in detail to `docker_watch`. Stats for those containers are exported without labels and therefore end up looking like duplicate values to prometheus.

**Comment by alexrudd** [comment]
I tested this locally and experienced the same problem. Tried curling the Docker stats api directly and couldn't see anything abnormal in the responses. I'll hopefully have time to look into this tomorrow.

**Comment by alexrudd** [comment]
Should be fixed!

By default docker_watch extracts all of a Docker container's labels and adds them as labels to the respective Prometheus metrics. Docker-compose adds some of its own labels to the Docker containers it runs, which use characters that aren't valid as Prometheus label keys (e.g `com.docker.compose.service`.)

I added some code to transform Docker labels to be purely alphanumberic strings.

**Comment by abhishekbajpayee** [comment]
Works on my end too. Thanks!

**Comment by abhishekbajpayee** [comment]
So `docker_watch` now seems to be exporting 2 copies of metrics for each compose stack container. If I query filter by `{name=~"..."}`, I see 2 series for each container in the compose stack. Should I be filtering based on some labels too?

**Comment by alexrudd** [comment]
Hey, I'm not seeing this same problem. Could you open up a new issue with some more details and steps to reproduce the problem.

Thanks!
